# Generated by Django 6.0.2 on 2026-02-28 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_part', models.CharField(choices=[('BRAZO', 'Brazo'), ('PIERNA', 'Pierna'), ('ESPALDA', 'Espalda'), ('PECHO', 'Pecho'), ('COSTILLAS', 'Costillas'), ('CUELLO', 'Cuello'), ('MANO', 'Mano'), ('PIE', 'Pie'), ('HOMBRO', 'Hombro'), ('ANTEBRAZO', 'Antebrazo')], max_length=20, verbose_name='Zona del Cuerpo')),
                ('size_cm', models.PositiveIntegerField(verbose_name='Tamaño (cm)')),
                ('is_color', models.BooleanField(default=False, verbose_name='¿A color?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('tattoo_style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_requests', to='artists.tattoostyle', verbose_name='Estilo de Tatuaje')),
            ],
            options={
                'verbose_name': 'Solicitud de Cotización',
                'verbose_name_plural': 'Solicitudes de Cotización',
                'ordering': ['-created_at'],
            },
        ),
    ]
