# Generated by Django 6.0.2 on 2026-04-19 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='Fecha y hora de la cita')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobada'), ('REJECTED', 'Rechazada'), ('COUNTER_OFFER', 'Contraoferta')], default='PENDING', max_length=15, verbose_name='Estado')),
                ('counter_offer_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora propuesta en contraoferta')),
                ('counter_offer_note', models.TextField(blank=True, default='', verbose_name='Nota de contraoferta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='artists.artistprofile', verbose_name='Artista')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('quote', models.ForeignKey(blank=True, help_text='Cotización a partir de la cual se generó esta cita.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='quotes.quoterequest', verbose_name='Cotización de origen')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(verbose_name='Inicio del bloqueo')),
                ('end_datetime', models.DateTimeField(verbose_name='Fin del bloqueo')),
                ('reason', models.TextField(blank=True, default='', help_text='Ej. vacaciones, evento privado, enfermedad.', verbose_name='Motivo del bloqueo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_blocks', to='artists.artistprofile', verbose_name='Artista')),
            ],
            options={
                'verbose_name': 'Bloqueo de Calendario',
                'verbose_name_plural': 'Bloqueos de Calendario',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='HealthConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_allergies', models.BooleanField(default=False, verbose_name='¿Tiene alergias?')),
                ('allergies_detail', models.TextField(blank=True, default='', help_text='Especificar si la respuesta anterior es Sí.', verbose_name='Descripción de alergias')),
                ('has_chronic_disease', models.BooleanField(default=False, help_text='Ej. diabetes, hipertensión, coagulopatías.', verbose_name='¿Padece enfermedad crónica?')),
                ('chronic_disease_detail', models.TextField(blank=True, default='', verbose_name='Descripción de enfermedad crónica')),
                ('takes_medication', models.BooleanField(default=False, help_text='Incluye anticoagulantes, corticosteroides, etc.', verbose_name='¿Toma medicamentos actualmente?')),
                ('medication_detail', models.TextField(blank=True, default='', verbose_name='Descripción de medicamentos')),
                ('is_pregnant', models.BooleanField(default=False, verbose_name='¿Está embarazada o en período de lactancia?')),
                ('has_skin_condition', models.BooleanField(default=False, help_text='Ej. psoriasis, queloide, dermatitis.', verbose_name='¿Tiene condiciones de piel?')),
                ('skin_condition_detail', models.TextField(blank=True, default='', verbose_name='Descripción de condición de piel')),
                ('terms_accepted', models.BooleanField(default=False, help_text='El cliente declara haber leído y aceptado los términos del servicio y el aviso de privacidad conforme a la Ley LFPDPPP.', verbose_name='Acepta términos y política de privacidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_consent', to='quotes.appointment', verbose_name='Cita')),
            ],
            options={
                'verbose_name': 'Cuestionario de Salud',
                'verbose_name_plural': 'Cuestionarios de Salud',
            },
        ),
    ]
