# Generated by Django 6.0.2 on 2026-05-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_add_appointment_healthconsent_calendarblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthconsent',
            name='has_hemophilia',
            field=models.BooleanField(default=False, help_text='Incluye hemofilia A, B, enfermedad de von Willebrand, etc.', verbose_name='¿Tiene hemofilia u otro trastorno de coagulación?'),
        ),
        migrations.AddField(
            model_name='healthconsent',
            name='hemophilia_detail',
            field=models.TextField(blank=True, default='', verbose_name='Descripción del trastorno de coagulación'),
        ),
        migrations.AddField(
            model_name='healthconsent',
            name='signature_data',
            field=models.TextField(default='', help_text='Imagen PNG de la firma del cliente codificada en base64.', verbose_name='Firma digital (base64)'),
        ),
    ]
