# Generated by Django 6.0.2 on 2026-02-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Cliente'), ('STUDIO', 'Estudio/Tatuador')], default='CLIENT', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
