# Generated by Django 6.0.2 on 2026-02-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('CLIENT', 'Cliente'), ('STUDIO', 'Estudio/Tatuador'), ('ADMIN', 'Administrador')], default='CLIENT', max_length=20, verbose_name='Tipo de Usuario'),
        ),
    ]
