# Generated by Django 6.0.2 on 2026-05-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_custom_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/profiles/', verbose_name='Foto de Perfil'),
        ),
    ]
