# Generated by Django 6.0.2 on 2026-02-28 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TattooStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Estilo de Tatuaje',
                'verbose_name_plural': 'Estilos de Tatuaje',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Biografía')),
                ('city', models.CharField(blank=True, default='', max_length=150, verbose_name='Ciudad')),
                ('base_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarifa por Hora')),
                ('minimum_setup_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarifa Mínima (apertura de agujas)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('styles', models.ManyToManyField(blank=True, related_name='artists', to='artists.tattoostyle', verbose_name='Estilos')),
            ],
            options={
                'verbose_name': 'Perfil de Artista',
                'verbose_name_plural': 'Perfiles de Artistas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/%Y/%m/', verbose_name='Imagen')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='artists.artistprofile', verbose_name='Artista')),
            ],
            options={
                'verbose_name': 'Imagen de Portafolio',
                'verbose_name_plural': 'Imágenes de Portafolio',
                'ordering': ['-created_at'],
            },
        ),
    ]
