# Generated by Django 6.0.2 on 2026-04-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_seed_tattoo_styles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioimage',
            options={'ordering': ['-position', '-created_at'], 'verbose_name': 'Imagen de Portafolio', 'verbose_name_plural': 'Imágenes de Portafolio'},
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
