# Generated by Django 6.0.2 on 2026-05-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_portfolioimage_options_portfolioimage_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Foto de Perfil'),
        ),
    ]
